### ISSUE TITLE
Best Field Strategy for anonymizing an array of Strings in Mongo?

### ISSUE THREAD

**Issue by ChrisC** [sunitparekh/data-anonymization#22]
I keep getting error 'Improper fields strategy defined' and I'm not sure what's the best field strategy to use in this case. Thanks!

**Comment by wpodgorski** [comment]
Can you write an example of how the code would look alike?

**Comment by sunitparekh** [comment]
There is a field strategy named AnonymizeArray which takes another strategy as input.
```
anonymize('alternate_emails').using FieldStrategy::AnonymizeArray.new(FieldStrategy::RandomMailinatorEmail.new)
```
have a look at the updated mongodb [example](https://github.com/sunitparekh/data-anonymization/blob/master/examples/mongodb_blacklist_dsl.rb#L24) line # 24 using [sample data](https://github.com/sunitparekh/data-anonymization/blob/master/sample-data/mongo/plans.json#L23)

I hope this helps. Feel free to message if you need further assistance.
