### ISSUE TITLE
Connecting to a MySQL Database in cPanel

### ISSUE THREAD

**Issue by srikanthvnv** [sunitparekh/data-anonymization#47]
Hi,
I am a newbie and don't know anything about using data anonymization technique nor running a Ruby Script. I have a Hospital Management System with Database records in MySQL in my cPanel. I want to use this tool to apply anonymization for my database. Please help. Thank you.

**Comment by sunitparekh** [comment]
Thank you for your interest in data anonymization. Please refer to [documentation](https://github.com/sunitparekh/data-anonymization) for using tool. To refer to example of usage please look at https://github.com/sunitparekh/data-anonymization/tree/master/examples. 

Also to learn more about concepts refer two articles http://www.sunitparekh.in/posts/data-anonymization and http://www.sunitparekh.in/posts/data-anonymization-techniques


I hope above information

**Comment by sunitparekh** [comment]
to install Ruby follow on http://rubyinstaller.org/ and to learn ruby you can lookup any online course https://www.codeschool.com/learn/ruby
