### ISSUE TITLE
MongoDB question : is it possible to anonymize a field that is a list of String

### ISSUE THREAD

**Issue by sylguyot** [sunitparekh/data-anonymization#64]
i want to anonymize such a document
{
    "_id" : ObjectId("5b06a729c27e0e706c93b432"),
    "cn" : [ 
        "sylvain guyot"
    ],
    "sn" : [ 
        "guyot"
    ],
    "givenName" : [ 
        "sylvain"
    ]
}

I have the following error with my code (anonymize('cn').using FieldStrategy::RandomFullName.new ):

E, [2018-05-25T07:38:37.171687 #100] ERROR -- : Errors while processing table 'annuaire_uid':
E, [2018-05-25T07:38:37.171766 #100] ERROR -- : no implicit conversion of String into Array (TypeError)

**Comment by sunitparekh** [comment]
Please have a look at this [example](https://github.com/sunitparekh/data-anonymization/blob/master/examples/mongodb_blacklist_dsl.rb#L26)
 for your use case. You need to wrap your strategy inside FieldStrategy::AnonymizeArray
like following

`FieldStrategy::AnonymizeArray.new(FieldStrategy::RandomFullName.new)`

**Comment by sylguyot** [comment]
Thank you, it's working!
