### ISSUE TITLE
Anonymization fails midway if two tables have a circular referential integrity

### ISSUE THREAD

**Issue by satyamag** [sunitparekh/data-anonymization#7]
Even though it is poor schema design there have been real world examples where it does happen.

**Comment by wasabigeek** [comment]
@sunitparekh it seems the corresponding Postgres options are:
- run ALTER TABLE on every table or defer each foreign key individually
- execute 'SET session_replication_role=replica;' for the session

The latter is a lot easier, but I need to set it within the actual session. Is there a way to include commands in the connection?

Also, what is `DisableReferentialIntegrityDatabase`? Was this an option you were thinking of adding?
https://github.com/sunitparekh/data-anonymization/blob/6ccfda43e077e32ec153ff3cf916d4622b146562/lib/utils/database.rb#L12
